### ISSUE TITLE
Delta Week 1 book

### ISSUE THREAD

**Issue by camilavargasp** [NCEAS/learning-hub-organization#60]

**Comment by camilavargasp** [comment]
**Book Prep**
- [ ] Create course branch
- [ ] See what needs to happen in the repro-research repository to deploy the book
- [ ] Update all sections to read in the correct Qmd according to the schedule
- [ ] Share with instructors the github workflow to contribute to the book
- [ ] make sure book renders and deployed with no issues

**Comment by camilavargasp** [comment]
**Fix**
- [ ] Rmd lesson. An issue with calling "ratio" in text
- [ ] Section 8: programmatic-data-access.qmd not working
- [ ] Section 12: r-practice-clean-wangle.qmd. `lobster_abundance_all_years_20220829` missing
- [ ] Check why Quarto chunk option format are not working

**Comment by camilavargasp** [comment]
## Chapters

- [ ] Check when ready
    - [ ] index.qmd # preface
    - [ ] session_01.qmd # rstudio server setup
    - [ ] session_02.qmd # git setup
    - [ ] session_03.qmd # mini intro to R programming + intro to rmd
    - [ ] session_04.qmd # LEGO activity
    - [ ] session_05.qmd # Accesing and publishing data
    - [ ] session_06.qmd # logic modeling
    - [ ] session_07.qmd # git and github intro
    - [ ] session_08.qmd # programmatic data access
    - [ ] session_09.qmd # data modeling essentials
    - [ ] session_10.qmd # synthesis
    - [ ] session_11.qmd # clean and wrangle data
    - [ ] session_12.qmd # r practice: clean and wrangling 
    - [ ] session_13.qmd # synthesis
    - [ ] session_14.qmd # r functions
    - [ ] session_15.qmd # r packages
    - [ ] session_16.qmd # FAIR and CARE
    - [ ] session_17.qmd # git collab
    - [ ] session_18.qmd # synthesis
    - [ ] session_19.qmd # reproducible papers

**Comment by hdolinh** [comment]
Hey @camilavargasp RE: Check why Quarto chunk option format are not working  **NOTE** Not sure why, but it works if I do Rmd style chunk options

I looked at the commits and in materials/sections/programmatic-data-access.qmd the r chunks with the Quarto code options have a space between the start of the r code chunk and the Quarto code options. It's nitpicky, but the code options don't execute when that space is there. In the examples below, I'm using apostrophes instead of backticks so you can see the code chunk formatting.

This doesn't work:
'''{r}

#| label: contentid-file-load
'''

This works:
'''{r}
#| label: contentid-file-load
'''

**Comment by hdolinh** [comment]
@camilavargasp RE: Section 12: r-practice-clean-wangle.qmd. lobster_abundance_all_years_20220829 missing

When I made these practice sessions, I set the yaml for each of the `session_XX.qmd` files to `eval: false` because none of the code in the practice sessions needs to run. The answers for each question are the lines of code, not the outputs of the code. So I never added the lobster data to the `nceas-training` repo. If I needed to access the lobster data in the book, I used the URL link and would hide the code chunk.

Also, the file paths to the data will always be different when running code in the book vs a participant so the code to read in `lobster_abundance_all_years_20220829` that's visible in the `r-practice-clean-wangle.qmd` is a reflection of what a participant would type out. 

LMK if you have any questions about this - happy to answer them

**Comment by hdolinh** [comment]
@camilavargasp RE: R clean and wrangle practice session:

Sounds good. One more thing I'll mention is that in both the `r-practice-owner-clean-wrangle.qmd` and the `r-practice-collaborator-clean-wrangle.qmd` files there is an "Extra Questions" section at the end that might be helpful for you. When I needed to shorten the practice session, I just made the questions not visible in the book but they're still there if you're looking for more cleaning and wrangling problems.

**Comment by mbjones** [comment]
@camilavargasp I restructured the book build pretty significantly today, making it a lot faster, and got the `redland` and `dataone` packages installing properly for section 08, which is now back in the build.  Lots more to do in the build to improve it, but it should be much faster now. I switched to using binary package builds from posit, and added an effective cache of the packages. So, if you need a new package, be sure its added to the `DESCRIPTION` file, which is what triggers a fresh install of the packages. If you don't change DESCRIPTION, then the build will use the cache. Details in issue #71, and let me know how it works for you when you push a chapter.

**Comment by camilavargasp** [comment]
Thanks @mbjones! The book is building and sooo much faster. I'll take a deep dive into GHA after the course to make sure we continue with the necessary updates. 
Thanks for documenting everything on an issue.
